services:
  zb-reader:
    image: ghcr.io/zuoban/zb-reader
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NEXTAUTH_SECRET=your-secret-key-change-this
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_TRUST_HOST=true
    restart: unless-stopped
